### PR TITLE
AUR: add wired-bin

### LINKED ISSUE #77: Feature: add wired-bin to AUR
As the title says, it would be great to have a pre-compiled file to avoid the compilation process. :)

### PR DESCRIPTION
**Pull request by jx11r**
* Closes #77 

Before adding the package to AUR, you must release a new version (0.10.3) to build the binary, comments welcome!

### CODE REVIEW

**Comment by Toqozz** [comment]
This looks great, thank you!

I don't have access to my computer for a while but will merge/make a new release when I get the chance.

**Comment by jx11r** [comment]
Np :)

**Comment by Toqozz** [comment]
Thanks!  Next time I make a release I'll push this AUR package as well.

**Comment by jx11r** [comment]
Awesome thanks!

**Pull request merged**
