### PR TITLE
nix: flake improvements

### PR DESCRIPTION
**Pull request by pleshevskiy**
- don't build app with naersk
- move overlays from flake-utils (See https://nixos.wiki/wiki/Flakes#Output_schema)
- add version to the wired package
- add ci to check nix flake and build legacy package

### CODE REVIEW

**Comment by pleshevskiy** [comment]
@Toqozz does `wired-notify` support darwin? Seems like dlib is not supported

```
error: Package ‘dlib-19.23’ in /nix/store/k2ifqlyrcv3sa4py1fk4cifdgba5ch86-source/pkgs/development/libraries/dlib/default.nix:34 is not supported on ‘aarch64-darwin’, refusing to evaluate.
```

So I can change supported platforms

**Comment by pleshevskiy** [comment]
Seems like `Nix packaging (legacy)` failed with `crates.io` issue 🤔 Can we restart job? I'm sure it should work now!

**Comment by pleshevskiy** [comment]
@Toqozz Tests passed. Any feedback?

**Comment by Toqozz** [comment]
Sorry, been a bit busy lately.  This seems fine :)

Thank you!

**Pull request merged**
